# Generated by Django 3.2.25 on 2024-07-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='prepTime',
        ),
    ]
